# -*- coding: utf-8 -*-
"""BARONIO_CodicePython_EsamePCP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkJ_GLz2uP4WO3xFQvNhMRCFv_gf_NTG

# Env Config
"""

"""
================================================================================
SISTEMA DI GESTIONE MAGAZZINO E ORDINI - LogiServe S.r.l.
================================================================================

Applicativo a riga di comando per la gestione di:
- Registrazione e monitoraggio ordini clienti
- Gestione giacenze e inventario magazzino
- Evasione ordini con aggiornamento automatico delle giacenze
- Alert per prodotti sotto soglia di riordino
- Generazione/export report giornalieri
- Import/Export dati magazzino e ordini
- Sistema di logging per tracciabilità operazioni

ARCHITETTURA:
------------
Il sistema è strutturato con le seguenti classi:
- Prodotto: gestione singolo articolo (codice, giacenza, punto riordino)
- Cliente: anagrafica cliente con storico ordini
- Ordine: gestione ordine con stati (nuovo/evaso/parziale/in attesa)
- Magazzino: inventario completo con operazioni su prodotti
- GestoreOrdini: gestione ordini e clienti
- Report: generazione report giornalieri

REQUISITI:
----------
- Python 3.7+
- Librerie standard: json, csv, datetime, logging, ast

================================================================================
"""

import json
import os
from datetime import datetime, timedelta
import csv
import ast
import logging

# Opzionale: scarica in formato csv un file con ordini da importare poi da riga di comando

data = """ORD001,ROSSI,2024-06-01,"{'P001': 80, 'P002': 80}"
ORD002,ROSSI,2024-06-02,"{'P003': 15}"
ORD003,VERDI,2024-06-01,"{'P001': 80, 'P002': 80}"
ORD004,ROSSI,2024-06-02,"{'P003': 15}"
ORD005,VERDI,2024-06-01,"{'P001': 80, 'P002': 80}"
ORD006,ROSSI,2024-06-02,"{'P003': 15}"
ORD007,VERDI,2024-06-01,"{'P001': 80, 'P002': 80}"
ORD008,ROSSI,2024-06-02,"{'P003': 15}"
ORD009,VERDI,2024-06-01,"{'P001': 80, 'P002': 80}"
ORD010,ROSSI,2024-06-02,"{'P003': 15}"
ORD011,VERDI,2024-06-01,"{'P001': 80, 'P002': 80}"
ORD012,ROSSI,2024-06-02,"{'P003': 15}"
"""

with open('ordini.csv', mode="w", newline="", encoding="utf-8") as csvfile:
    writer = csv.writer(csvfile)

    for line in data.strip().split("\n"):
        row = next(csv.reader([line]))
        writer.writerow(row)

print(f"File '{'ordini.csv'}' creato con successo.")

# Questa funzione viene richiamata all'inizio del main per popolare catalogo prodotti e registro clienti.

def setting_environment(logger):

  # Popolo il dizionario dei clienti
  clienti = {
      'ROSSI' : Cliente('ROSSI', 'Rossi Mario', 'Rossi SRL', 'rossi@mail.com', '+39 02020202', indirizzo="Via XXX"),
      'VERDI' : Cliente('VERDI', 'Verdi Luigi', 'Verdi SPA', 'verdi@mail.com', '+39 03030303', indirizzo="Via XXX"),
      'GIALLI' : Cliente('GIALLI', 'Gialli Wario', 'Gialli SRLS', 'gialliwario@hotmail.it', '+39 90909090', indirizzo='Via YYY'),
      'VIOLA' : Cliente('VIOLA', 'Viola Waluigi', 'Waluigi SNC', 'waluigi@mail.com', '+39 04040404', indirizzo="Via XXX")}

  # Inizializzo il Gestore Ordini, il Magazzino, il Report e il logger
  gestore_ordini = GestoreOrdini(clienti=clienti)
  magazzino = Magazzino()
  report = Report()
  logger.info("Gestore ordini, magazzino e report inizializzati")

  # Popolo il magazzino
  p001 = Prodotto('P001', 'Rubinetto', 'Idraulica', 200, 20, 'pz')
  p002 = Prodotto('P002', 'Tubo', 'Idraulica', 300, 30, 'pz')
  p003 = Prodotto('P003', 'Martello', 'Attrezzi', 500, 20, 'pz')
  p004 = Prodotto('P004', 'WD-40', 'Liquidi', 1000, 100, 'lt')
  p005 = Prodotto('P005', 'Tubetto', 'Idraulica', 4000, 200, 'mt')
  p006 = Prodotto('P006', 'Fiorino a metano', 'Automobili', 10, 2, 'pz')
  p007 = Prodotto('P007', 'Piatto doccia', 'Idraulica', 100, 20, 'pz')

  magazzino.aggiungi_prodotto(p001)
  magazzino.aggiungi_prodotto(p002)
  magazzino.aggiungi_prodotto(p003)
  magazzino.aggiungi_prodotto(p004)
  magazzino.aggiungi_prodotto(p005)
  magazzino.aggiungi_prodotto(p006)
  magazzino.aggiungi_prodotto(p007)

  return gestore_ordini, magazzino, report, clienti

"""# Classi

## Class Prodotto
"""

class Prodotto:

  def __init__(self, codice, nome, categoria, giacenza, punto_riordino, unita_misura):
    self.codice = codice
    self.nome = nome
    self.categoria = categoria
    self.giacenza = giacenza
    self.punto_riordino = punto_riordino
    self.unita_misura = unita_misura

  def aggiorna_giacenza(self, quantita):
    '''
    self.giacenza : giacenza del prodotto in magazzino
    quantita : quantità che viene aggiunta in magazzino / tolta dal magazzino

    La funzione permette di aggiornare la giacenza in base ai movimenti di magazzino
    '''
    quantita = int(quantita)
    nuova = self.giacenza + quantita
    if nuova < 0:
      raise ValueError("La giacenza non può diventare negativa.")
    self.giacenza = nuova

  def __str__(self):
    '''
    Rappresentazione testuale del prodotto
    '''
    return (f"Codice: {self.codice} - Nome: {self.nome} "
        f"(Categoria: {self.categoria}) - Giacenza: {self.giacenza}/{self.punto_riordino} {self.unita_misura}")


  def necessita_riordino(self):
    '''
    Permette di ricevere un bool correlato alla necessità o meno di riordinare un prodotto
    '''
    return self.giacenza < self.punto_riordino

  def check_disponibilita(self, quantita_richiesta):
    '''
    quantita_richiesta : int - quantità che si vuole prelevare

    Return:
    bool - True se c'è abbastanza giacenza, False altrimenti
    '''
    return self.giacenza >= quantita_richiesta  # >= non > (se chiedo 10 e ho 10, va bene!)

# Esempio
# interruttore = Prodotto(codice="INT001", nome="Interruttore", categoria="Elettrico", giacenza=100, punto_riordino=20, unita_misura="pz")

"""## Class Cliente"""

class Cliente:

    def __init__(self, id_cliente, nome, ragione_sociale, email, telefono, indirizzo=""):
        '''
        Inizializza un nuovo cliente

        Parametri:
        id_cliente: str - identificativo univoco del cliente
        nome: str - nome del referente
        ragione_sociale: str - nome dell'azienda cliente
        email: str - email di contatto
        telefono: str - numero di telefono
        indirizzo: str - indirizzo (opzionale)
        '''
        self.id_cliente = id_cliente
        self.nome = nome
        self.ragione_sociale = ragione_sociale
        self.email = email
        self.telefono = telefono
        self.indirizzo = indirizzo
        self.storico_ordini = []  # Lista di id_ordine

    def aggiungi_ordine(self, id_ordine):
        '''
        Aggiunge un ordine allo storico del cliente

        Parametri:
        id_ordine: str - ID dell'ordine da aggiungere
        '''
        self.storico_ordini.append(id_ordine)

    def __str__(self):
        '''
        Rappresentazione testuale del cliente
        '''
        return (f"Cliente #{self.id_cliente} - {self.ragione_sociale} "
                f"(Ref: {self.nome}) - Email: {self.email} - "
                f"Ordini totali: {len(self.storico_ordini)}")

# Esempio di utilizzo:
# ROSSI = Cliente(
#     id_cliente="CLI001",
#     nome="Mario Rossi",
#     ragione_sociale="Elettro Rossi S.r.l.",
#     email="m.rossi@elettrorossi.it",
#     telefono="+39 02 1234567"
# )

"""## Class Ordine"""

class Ordine:

  def __init__(self, id_ordine, cliente, data, prodotti, priorita="normale"):
    self.id_ordine = id_ordine
    self.cliente = cliente # riferimento all'oggetto Cliente
    self.data = data
    self.priorita = priorita
    self.prodotti = prodotti
    self.stato = "nuovo"

  def __str__(self):
    '''
    Print dell'ordine formattato
    '''
    return (f"Ordine #{self.id_ordine} - Cliente: {self.cliente.ragione_sociale} - "
            f"Data: {self.data} - Stato: {self.stato} - "
            f"Prodotti: {self.prodotti}")

  def cambia_stato(self, nuovo_stato):
    '''
    Cambia lo stato dell'ordine

    Parametri:
    nuovo_stato = str - può essere 'nuovo', 'evaso', 'parziale', 'in attesa'
    '''
    stati_validi = ('nuovo', 'evaso', 'parziale', 'in attesa')
    assert nuovo_stato in stati_validi, f"Stato non consentito: {nuovo_stato}"
    self.stato = nuovo_stato

  def cambia_quantita(self, codice_prodotto, nuova_quantita):
    '''
    Cambia la quantità di un prodotto nell'ordine.
    Se il prodotto esiste, aggiorna la quantità.
    Se la quantità è zero o negativa, rimuove il prodotto.
    Se il prodotto non esiste, lo aggiunge se la quantità è positiva.
    '''
    if codice_prodotto in self.prodotti:
      if nuova_quantita > 0:
        self.prodotti[codice_prodotto] = nuova_quantita
      else:
        # Rimuovi il prodotto se la quantita non è positiva
        self.prodotti.pop(codice_prodotto)
    else:
      if nuova_quantita > 0:
        self.prodotti[codice_prodotto] = nuova_quantita
      else:
        raise ValueError("Quantità non valida per aggiungere un nuovo prodotto.")

  def modifica_ordine(self):
    codice_prodotto = input("Inserisci il codice del prodotto da modificare: ")
    if codice_prodotto in self.prodotti:
      try:
        nuova_quantita = int(input(f"Prodotto {codice_prodotto} trovato, inserisci nuova quantità: "))
        self.cambia_quantita(codice_prodotto, nuova_quantita)
      except ValueError as e:
        print(f"Errore: {e}")
    else:
      risposta = input(f"Prodotto {codice_prodotto} non trovato. Vuoi aggiungerlo? [s/N]")
      if risposta.lower() == "s":
        try:
          nuova_quantita = int(input("Inserisci la quantità da aggiungere: "))
          self.cambia_quantita(codice_prodotto, nuova_quantita)
          print(f"Prodotto {codice_prodotto} aggiunto con quantità {nuova_quantita}")
        except ValueError as e:
          print(f"Errore: {e}")
      else:
        print(f"Nessuna modifica effettuata")

# Esempio
# ROSSI = Cliente(id_cliente="CLI001", nome="Mario Rossi", ragione_sociale="Elettro Rossi S.r.l.",
#                    email="m.rossi@elettrorossi.it", telefono="+39 02 1234567")
# ordine1 = Ordine(id_ordine="001", cliente=ROSSI, data="2024-06-01", prodotti={'magliette': 10})
# print(ordine1)

"""## Class Magazzino"""

class Magazzino:

  def __init__(self):
    self.prodotti = {}  # Dizionario vuoto: {codice: oggetto_Prodotto}

  def aggiungi_prodotto(self, prodotto):
    '''
    Aggiunge un nuovo prodotto al magazzino
    prodotto: oggetto di tipo Prodotto
    '''
    if prodotto.codice in self.prodotti:
      raise ValueError(f"Prodotto {prodotto.codice} già presente nel magazzino.")
    self.prodotti[prodotto.codice] = prodotto

  def cerca_prodotto_id(self, codice):
    '''
    Cerca e restituisce un prodotto dato il codice
    return: oggetto Prodotto o None se non esiste
    '''
    prodotto = self.prodotti.get(codice)
    if prodotto is None:
      raise ValueError(f"Prodotto con codice '{codice}' non trovato nel magazzino.")

    return prodotto

  def cerca_prodotto_categoria(self, categoria):
    '''
    Cerca e restituisce un prodotto data la categoria
    return: oggetto Prodotto o None se non esiste
    '''
    risultati = []
    for prodotto in self.prodotti.values():
      if prodotto.categoria == categoria:
        risultati.append(str(prodotto))
    if len(risultati) == 0:
      raise ValueError(f"Prodotto con categoria '{categoria}' non trovato nel magazzino.")

    return risultati

  def cerca_prodotto_giacenza(self, soglia):
    '''
    Cerca e restituisce i prodotti con giacenza inferiore o uguale alla soglia
    return: lista di oggetti Prodotto (anche vuota se non ci sono risultati
    '''

    risultati = []
    for prodotto in self.prodotti.values():
      if prodotto.giacenza <= soglia:
        risultati.append(str(prodotto))
    if len(risultati) == 0:
      raise ValueError(f"Nessun prodotto con giacenza inferiore a {soglia} trovato nel magazzino.")

    return risultati

  def visualizza_inventario(self):
    '''
    Crea dizionario con tutti i prodotti e le loro giacenze
    '''
    inventario = []
    for codice, prodotto in self.prodotti.items():
      inventario.append({
          'codice':codice,
          'nome':prodotto.nome,
          'giacenza':prodotto.giacenza,
          'unita_misura':prodotto.unita_misura
      })
    return inventario

  def prodotti_da_riordinare(self):
    '''
    Restituisce una lista di dizionari con prodotti la cui giacenza è inferiore al punto di riordino
    '''
    da_riordinare = []
    for prodotto in self.prodotti.values():
        if prodotto.necessita_riordino():
            da_riordinare.append({
                'codice': prodotto.codice,
                'nome': prodotto.nome,
                'giacenza': prodotto.giacenza,
                'punto_riordino': prodotto.punto_riordino
            })
    return da_riordinare

  def esporta_inventario_json(self, nome_file):
    inventario = self.visualizza_inventario()
    with open(nome_file, 'w', encoding='utf-8') as f:
      json.dump(inventario, f, indent=2)

    return nome_file

  def importa_inventario_json(self, nome_file):
      with open(nome_file, 'r', encoding='utf-8') as f:
          inventario = json.load(f)

      for item in inventario:
          codice = item['codice']
          # Verifica se il prodotto esiste già nel magazzino
          if codice in self.prodotti:
              prodotto = self.prodotti[codice]
              # Aggiorna le proprietà essenziali
              prodotto.nome = item.get('nome', prodotto.nome)
              prodotto.giacenza = item.get('giacenza', prodotto.giacenza)
              prodotto.punto_riordino = item.get('punto_riordino', prodotto.punto_riordino)
              prodotto.unita_misura = item.get('unita_misura', prodotto.unita_misura)
          else:
              # Crea un nuovo prodotto se non esiste
              nuovo_prodotto = Prodotto(
                  codice=codice,
                  nome=item['nome'],
                  categoria=item.get('categoria', ''),
                  giacenza=item.get('giacenza', 0),
                  punto_riordino=item.get('punto_riordino', 0),
                  unita_misura=item.get('unita_misura', '')
              )
              self.aggiungi_prodotto(nuovo_prodotto)

      # True per indicare import avvenuto correttamente
      return True

  def stampa_inventario(self):
    '''
    Stampa inventario in formato leggibile
    '''
    for prodotto in self.prodotti.values():
      sotto_soglia = prodotto.giacenza < prodotto.punto_riordino
      flag = " *" if sotto_soglia else ""
      print(f"Codice: {prodotto.codice} - Prodotto: {prodotto.nome} - Giacenza: {prodotto.giacenza}/{prodotto.punto_riordino} {prodotto.unita_misura}{flag}")

  def stampa_prodotti_da_riordinare(self):
    '''
    Stampa i prodotti con giacenza inferiore al punto di riordino stabilito in formato leggibile
    '''
    risultato = ""
    for prodotto in self.prodotti.values():
      if prodotto.necessita_riordino():
        risultato += (f"{prodotto.codice}: {prodotto.nome} - Giacenza {prodotto.giacenza}/{prodotto.punto_riordino}\n")

    if risultato == "":
        return "Nessun prodotto da riordinare"
    else:
      print(risultato)

"""## Class GestoreOrdini"""

class GestoreOrdini:

  def __init__(self, clienti=None):
    self.clienti = clienti if clienti is not None else {}
    self.ordini = {} # {id_ordine : oggetto_Ordine}

  def visualizza_ordini(self):
    '''
    Stampa tutti gli ordini
    '''
    lista = []
    for ordine in self.ordini.values():
      lista.append(f"Ordine {ordine.id_ordine} - Ordinante: {ordine.cliente.ragione_sociale} - Data ordine: {ordine.data} - Stato: {ordine.stato}")

    return lista

  def registra_ordine(self, ordine):
    '''
    Aggiunge un nuovo ordine al gestore

    Parametri:
    ordine: oggetto di tipo Ordine
    '''
    self.ordini[ordine.id_ordine] = ordine

  def check_data(self):
    '''
    Controlla che la data sia nel formato corretto
    '''
    while True:
      data_input = input("Inserisci la data dell'ordine (formato YYYY-MM-DD): ")
      try:
        datetime.strptime(data_input, "%Y-%m-%d")
        return data_input
      except ValueError:
        print("Data non valida, assicurati di inserire la data nel formato corretto (YYYY-MM-DD).")

  def registra_cliente_da_input(self):
    '''
    Registra un nuovo cliente a partire dai dati inseriti dall'utente

    Return: oggetto di tipo Cliente
    '''
    while True:
      id_cliente = input("Inserisci l'ID univoco del cliente: ")
      if id_cliente in self.clienti:
        print(f"Errore: un cliente con ID '{id_cliente}' esiste già.")
      else:
        break # ID UNICO

    nome = input("Inserisci il nome del cliente: ")
    ragione_sociale = input("Inserisci la ragione sociale del cliente: ")
    email = input("Inserisci l'email del cliente: ")
    telefono = input("Inserisci il numero di telefono del cliente: ")
    indirizzo = input("Inserisci l'indirizzo del cliente (opzionale): ")
    cliente = Cliente(id_cliente, nome, ragione_sociale, email, telefono, indirizzo)
    self.clienti[cliente.id_cliente] = cliente

    return cliente

  def crea_e_registra_ordine_da_input(self, id_cliente_str):
    '''
    Crea un nuovo ordine a partire dai dati inseriti dall'utente

    Parametri:
    id_cliente_str: str - ID del cliente a cui associare l'ordine

    Return: oggetto di tipo Cliente
    '''
    if id_cliente_str in self.clienti:
      cliente = self.clienti[id_cliente_str]

      id_ordine = input("Inserisci l'ID dell'ordine: ")
      data = self.check_data()
      prodotti = {}

      while True:
        codice_prodotto = input("Inserisci il codice del prodotto:")
        while True:
          quantita_input = input("Inserisci la quantità: ")
          try:
            quantita = int(quantita_input)
            break
          except ValueError:
            print("Quantità non valida. Assicurati di inserire un numero intero.")

        prodotti[codice_prodotto] = quantita

        continuare = input("Vuoi inserire altri prodotti? [s/N]")
        if continuare.lower() != 's':
          break

      ordine = Ordine(id_ordine, cliente, data, prodotti)
      self.registra_ordine(ordine)

    else:
      print(f"Cliente con ID '{id_cliente_str}' non trovato.")
      input_menu1 = input("Procedere con registrazione del cliente? [s/N]")
      if input_menu1.lower() == 's':
        cliente = self.registra_cliente_da_input()
        self.clienti[cliente.id_cliente] = cliente
        id_ordine = input("Inserisci l'ID dell'ordine: ")
        data = input("Inserisci la data dell'ordine (formato YYYY-MM-DD): ")
        prodotti = {}
        while True:
          codice_prodotto = input("Inserisci il codice del prodotto:")
          quantita = int(input("Inserisci la quantità: "))
          prodotti[codice_prodotto] = quantita
          continuare = input("Vuoi inserire altri prodotti? [s/N]")
          if continuare.lower() != 's':
            break
        ordine = Ordine(id_ordine, cliente, data, prodotti)
        self.registra_ordine(ordine)
      else:
        print("Registrazione cliente non avvenuta.")
        return None

    return ordine

  def import_ordini_csv(self, nome_file):
    '''
    Importa ordini da un file CSV

    Parametri:
    nome_file (str): nome del file CSV da importare.

    Return: lista di oggetti Ordine
    '''
    ordini_registrati = []  # per tenere traccia di ordini importati

    with open(nome_file, 'r', encoding='utf-8') as f:
      reader = csv.reader(f, delimiter=',')

      for line_num, line in enumerate(reader, start=1):
        try:
          id_ordine, id_cliente, data, prodotti_str = line
          prodotti = ast.literal_eval(prodotti_str)
        except ValueError as e:
          print(f"Errore parsing riga {line_num}: {e}")
          continue

        cliente = self.clienti.get(id_cliente)
        if cliente is None:
          print(f"Cliente con ID '{id_cliente}' non trovato nella riga {line_num}. Ordine saltato.")
          continue

        ordine = Ordine(id_ordine, cliente, data, prodotti)

        self.registra_ordine(ordine)
        cliente.aggiungi_ordine(id_ordine)
        ordini_registrati.append(ordine)

    return ordini_registrati

  def cerca_ordine(self, id_ordine):
    '''
    Cerca l'ordine e restituisce l'id dell'ordine
    Return: oggetto Ordine o None
    '''
    return self.ordini.get(id_ordine)

  def ordini_per_stato(self, stato):
    '''
    Restituisce lista di ordini con un certo stato
    stato: 'nuovo', 'evaso', 'parziale', 'in attesa'
    Return: lista di oggetti Ordine
    '''
    ordini = []
    for ordine in self.ordini.values():
      if ordine.stato == stato:
        ordini.append(ordine)

    return ordini

  def evadi_ordine(self, id_ordine, magazzino):
    '''
    Evade un ordine aggiornando le giacenze del magazzino.
    Se la giacenza non è sufficiente evaade la quantità disponibile

    Parametri:
    id_ordine: str - ID dell'ordine da evadere
    magazzino: oggetto Magazzino

    Return: stringa con esito
    '''
    messaggi = []
    # STEP 1: Cerca l'ordine
    ordine = self.cerca_ordine(id_ordine)
    if ordine is None:
      raise ValueError('Ordine non trovato.')

    # STEP 2: Inizializza contatori
    prodotti_evasi_completi = 0
    prodotti_evasi_parziali = 0
    prodotti_non_evasi = 0
    prodotti_totali = len(ordine.prodotti)

    # STEP 3: Cicla sui prodotti dell'ordine
    prodotti_evasi = {}

    for codice_prodotto, quantita in ordine.prodotti.items():
      # Cerca prodotto nel magazzino
      try:
        # Controlla disponibilità
        if quantita <= 0:
          raise ValueError(f'Quantità non valida ({quantita} per prodotto {codice_prodotto})')

        prodotto = magazzino.cerca_prodotto_id(codice_prodotto)

        # Determina quantità da evadere
        if prodotto.giacenza >= quantita:
          # EVASIONE COMPLETA
          quantita_evasa = quantita
          prodotto.aggiorna_giacenza(-quantita_evasa)
          prodotti_evasi_completi += 1
          messaggi.append(f'Evasi {quantita_evasa} x {codice_prodotto}')

        elif prodotto.giacenza > 0:
          # EVASIONE PARZIALE
          quantita_evasa = prodotto.giacenza
          prodotto.aggiorna_giacenza(-quantita_evasa)
          prodotti_evasi_parziali += 1
          messaggi.append(f'Evasi {quantita_evasa} x {codice_prodotto}')

        elif prodotto.giacenza == 0:
          # NON DISPONIBILE
          quantita_evasa = 0
          prodotti_non_evasi += 1
          messaggi.append(f'Non evasi {quantita_evasa} x {codice_prodotto}')

        # Tracciamento quantità evasa
        prodotti_evasi[codice_prodotto] = quantita_evasa

      except ValueError as e:
        messaggi.append(f"Errore ordine {id_ordine}, prodotto {codice_prodotto}: {e}")
        continue

    # STEP 4: Determina stato finale
    if prodotti_evasi_completi == prodotti_totali:
        ordine.cambia_stato("evaso")
        esito = "COMPLETAMENTE EVASO"
    elif prodotti_evasi_completi + prodotti_evasi_parziali > 0:
        ordine.cambia_stato("parziale")
        esito = "PARZIALMENTE EVASO"
    else:
        ordine.cambia_stato("in attesa")
        esito = "NON EVASO"

    # STEP 5: Restituisci risultato
    messaggi.append(f"Ordine {ordine.id_ordine}: {esito}\n - Prodotti evasi: {prodotti_evasi}/{prodotti_totali}")
    return messaggi

  def esporta_ordini_json(self):
    '''
    Esporta tutti gli ordini in un file JSON.

    Return: nome del file JSON
    '''
    ordini = []
    for ordine in self.ordini.values():
      ordini.append({
          'id_ordine': ordine.id_ordine,
          'cliente': ordine.cliente.id_cliente,
          'data': ordine.data,
          'prodotti': ordine.prodotti,
          'stato': ordine.stato
      })

    with open(f"registro_ordini_{datetime.now().date()}.json", 'w', encoding='utf-8') as f:
      json.dump(ordini, f, indent=2)

    return f"registro_ordini_{datetime.now().date()}.json"

  def import_ordini_json(self, nome_file):
    '''
    Importa ordini da un file JSON.

    Parametri:
    nome_file (str): nome del file JSON da importare.

    Return: lista di oggetti Ordine
    '''
    with open(nome_file, 'r', encoding='utf-8') as f:
      ordini = json.load(f)
    for ordine_data in ordini:
      id_ordine = ordine_data['id_ordine']
      cliente_id = ordine_data['cliente']
      cliente = self.clienti.get(cliente_id)
      if cliente is None:
        print(f"Cliente con ID '{cliente_id}' non trovato. Ordine saltato.")
        continue
      data = ordine_data['data']
      prodotti = ordine_data['prodotti']
      stato = ordine_data['stato']
      ordine = Ordine(id_ordine, cliente, data, prodotti, stato)
      self.registra_ordine(ordine)
      cliente.aggiungi_ordine(id_ordine)

    return ordini

"""## Class Report"""

class Report:
  def __init__(self, data=None):
    '''
    Inizializza il report con una data.

    data (str): data in formato yymmdd10. Se None, usa la data odierna.
    data = datetime.today().strftime('%Y-%m-%d')
    '''
    if data is None:
      self.data = datetime.today().strftime('%Y-%m-%d')
    else:
      self.data = data

  def calcola_ordini(self, gestore_ordini):
    '''
    Calcola il numero di ordini nuovi, attivi e parziali.

    Parametri:
    gestore_ordini (GestoreOrdini): oggetto che gestisce gli ordini

    Ritorno:
    dict: ordini nuovi, attivi e parziali.
    '''
    conteggio_stati = {'nuovo' : 0,
                       'evaso' : 0,
                       'parziale' : 0,
                       'in attesa' : 0}

    for ordine in gestore_ordini.ordini.values():
      if ordine.stato in conteggio_stati:
        conteggio_stati[ordine.stato] += 1

    return conteggio_stati

  def calcola_prodotti_piu_venduti(self, gestore_ordini):
    '''
    Calcola la classifica dei prodotti più venduti.

    Parametri:
    gestore_ordini (GestoreOrdini): oggetto che gestisce gli ordini.

    Ritorno:
    dict: prodotti e quantità vendute.
    '''
    vendite = {}
    for ordine in gestore_ordini.ordini.values():
      if ordine.stato in ['evaso', 'parziale']:
        for codice, quantita in ordine.prodotti.items():
          vendite[codice] = vendite.get(codice, 0) + quantita

    return vendite

  def calcola_stato_magazzino(self, magazzino):
    '''
    Calcola lo stato attuale del magazzino, ad esempio prodotti a catalogo,
    prodotti sotto soglia riordino, ecc.

    Parametri:
    magazzino (Magazzino): oggetto che rappresenta il magazzino.

    Ritorno:
    dict: statistiche sullo stato del magazzino.
    '''
    totale_prodotti = len(magazzino.prodotti)
    sotto_riordino = sum(1 for p in magazzino.prodotti.values() if p.necessita_riordino())

    return {
        'totale_prodotti' : totale_prodotti,
        'prodotti_sotto_riordino' : sotto_riordino
    }

  def prodotti_sotto_riordino(self, magazzino):
    '''
    Restituisce la lista dei prodotti che necessitano di riordino.

    Parametri:
    magazzino (Magazzino): oggetto che rappresenta il magazzino.

    Ritorno:
    list: prodotti da riordinare.
    '''
    prodotti_riordino = [p['codice'] for p in magazzino.prodotti_da_riordinare()]

    return prodotti_riordino

  def calcola_variazione_giacenze(self, gestore_ordini):
    '''
    Calcola la variazione delle giacenze rispetto al giorno precedente.

    Parametri:
    gestore_ordini (Gestore): oggetto che rappresenta il magazzino.

    Ritorno:
    dict: variazioni delle giacenze.
    '''
    variazione = {}
    stati_filtrati = ['evaso', 'parziale']
    for ordine in gestore_ordini.ordini.values():
        if ordine.stato in stati_filtrati:
            for prodotto, quantita in ordine.prodotti.items():
                variazione[prodotto] = variazione.get(prodotto, 0) + quantita

    return variazione

  def genera_report(self, gestore_ordini, magazzino):
    '''
    Genera il report completo come stringa formattata.

    Parametri:
    gestore_ordini (GestoreOrdini): oggetto che gestisce gli ordini.
    magazzino (Magazzino): oggetto che rappresenta il magazzino.

    Ritorno:
    str: testo del report.
    '''
    righe_report = []

    # Header
    righe_report.append("="*59)
    righe_report.append("-"*20+f" REPORT {self.data} "+ "-"*20)
    righe_report.append("="*59)
    righe_report.append("\n")

    # 1. Riepilogo ordini per stato

    righe_report.append('1. RIEPILOGO ORDINI PER STATO\n')
    for tipo_ordine, numero in self.calcola_ordini(gestore_ordini).items():
      righe_report.append(f'Ordini in stato "{tipo_ordine}": {numero}')

    righe_report.append("\n"+"-"*59+"\n")

    # 2. Prodotti più venduti

    righe_report.append('2. PRODOTTI PIù VENDUTI (ordinati in maniera decrescente)\n')

    vendite = self.calcola_prodotti_piu_venduti(gestore_ordini)
    if vendite:
      # Ordinamento decrescente
      prodotti_ordinati = sorted(vendite.items(), key=lambda x: x[1], reverse=True)
      top_5_prodotti = prodotti_ordinati[:5]

      for prodotto, n_vendite in top_5_prodotti:
        righe_report.append(f"Prodotto {prodotto}: {n_vendite} vendite")
    else:
      righe_report.append('Nessun prodotto acquistato.')

    righe_report.append("\n"+"-"*59+"\n")

    # 3. Stato magazzino

    righe_report.append(f'3. STATO MAGAZZINO\n')
    stato = self.calcola_stato_magazzino(magazzino)
    n_totale = stato['totale_prodotti']
    n_riordino = stato['prodotti_sotto_riordino']
    righe_report.append(f'Numero totale di prodotti in magazzino: {n_totale}')
    righe_report.append(f'Numero di prodotti in riordino: {n_riordino}')

    righe_report.append("\n"+"-"*59+"\n")

    # 4. Prodotti sotto riordino

    righe_report.append(f'4. PRODOTTI SOTTO RIORDINO\n')
    prodotti_sotto_riordino_mag = self.prodotti_sotto_riordino(magazzino)
    if prodotti_sotto_riordino_mag:
      for elemento in prodotti_sotto_riordino_mag:
        righe_report.append(f"- {elemento}")
    else:
      righe_report.append('Nessun prodotto sotto soglia di riordino.')

    righe_report.append("\n"+"-"*59+"\n")

    # 5. Variazione giacenze

    righe_report.append(f'5. VARIAZIONE GIACENZE\n')
    var_giacenze = self.calcola_variazione_giacenze(gestore_ordini).items()
    if var_giacenze:
      for prodotto, var_giacenza in var_giacenze:
        unita_misura = magazzino.cerca_prodotto_id(prodotto).unita_misura
        righe_report.append(f'Prodotto {prodotto}: uscita di {var_giacenza} {unita_misura}')
    else:
      righe_report.append('Nessuna variazione di giacenze.')

    righe_report.append("\n")

    righe_report.append("="*59)
    righe_report.append("-"*23+f" FINE REPORT "+ "-"*23)
    righe_report.append("="*59)

    return '\n'.join(righe_report)

  def esporta_report_txt(self, gestore_ordini, magazzino, nome_file=None):
    '''
    Esporta il report in un file di testo.

    Parametri:
    gestore_ordini (GestoreOrdini): oggetto che gestisce gli ordini.
    magazzino (Magazzino): oggetto che rappresenta il magazzino.
    nome_file (str, opzionale): nome del file di output. Se None, usa un nome standard.

    Ritorno:
    str: nome del file creato oppure None in caso di errore.
    '''
    try:
      report = self.genera_report(gestore_ordini, magazzino)
      if nome_file is None:
        nome_file = f'report_{self.data}.txt'

      with open(nome_file, 'w', encoding='utf-8') as f:
        f.write(report)

      return nome_file

    except Exception as e:
      print(f'Errore durante esportazione report: {e}')
      return None

"""# MAIN (\_\_main\_\_)"""

# Definizione funzioni per menu
def menu():
  print("\nScegli una operazione:")
  print("1. Registrazione nuovi ordini")
  print("2. Visualizza o evadi ordini")
  print("3. Consultazione magazzino")
  print("4. Creazione report")
  print("5. Salvataggio DB in JSON")
  print("0. Esci")
  scelta = input("Inserisci il numero dell'operazione: ")
  return scelta

def menu_1():
  print("\nScegli un'operazione:")
  print("1. Registrazione nuovo ordine (manuale)")
  print("2. Registrazione nuovo ordine (csv)")
  scelta_1 = input("Inserisci il numero dell'operazione: ")
  return scelta_1

def menu_2():
  print("\nScegli un'operazione:")
  print("1. Visualizzazione degli ordini")
  print("2. Evasione ordine")
  scelta_2 = input("Inserisci il numero dell'operazione: ")
  return scelta_2

def menu_3():
  print("\nScegli un'operazione:")
  print("1. Visualizzazione del magazzino")
  print("2. Modifica giacenze prodotto")
  print("3. Ricerca prodotti")
  scelta_3 = input("Inserisci il numero dell'operazione: ")
  return scelta_3

def menu_3_3():
  print("\nScegli un'operazione:")
  print("1. Ricerca prodotto tramite codice")
  print("2. Ricerca prodotto tramite categoria")
  print("3. Ricerca prodotto tramite giacenza")
  scelta_3_3 = input("Inserisci il numero dell'operazione: ")
  return scelta_3_3

def menu_5():
  print("\nScegli un'operazione:")
  print("1. Esportazione magazzino in JSON")
  print("2. Importazione magazzino in JSON")
  print("3. Esportazione lista ordini in JSON")
  print("4. Importazione lista ordini in JSON")

  scelta_5 = input("Inserisci il numero dell'operazione: ")

  return scelta_5

# Definizione del logger
def configura_logger():
  '''
  Configura il logger per registrare le operazioni su file.
  '''
  logger = logging.getLogger('WarehouseApp_Logiserve')
  logger.setLevel(logging.INFO)

  file_handler = logging.FileHandler('app.log', encoding='utf-8')
  file_handler.setLevel(logging.INFO)

  formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
  file_handler.setFormatter(formatter)

  logger.addHandler(file_handler)
  return logger

# Definizione del check per prodotti sotto soglia
def controlla_ordine_sotto_soglia(ordine, magazzino):
  '''
  Controlla se l'ordine contiene prodotti sotto la soglia di riordino.
  '''
  prodotti_critici = []
  for codice_prodotto in ordine.prodotti.keys():
    try:
      prodotto = magazzino.cerca_prodotto_id(codice_prodotto)
      if prodotto.necessita_riordino():
        prodotti_critici.append((codice_prodotto, prodotto.giacenza, prodotto.punto_riordino))
    except ValueError:
      pass
  return prodotti_critici

def mostra_alert_sotto_soglia(prodotti_critici):
  '''
  Mostra un alert all'utente per i prodotti sotto soglia.
  '''
  if prodotti_critici:
    print("\n" + "="*60)
    print("--- PRODOTTI SOTTO SOGLIA DI RIORDINO--- ")
    print("="*60)
    for codice, giacenza, soglia in prodotti_critici:
      print(f"  • Prodotto: {codice} - Giacenza: {giacenza}/{soglia}")
    print("="*60 + "\n")

# ==============================================================================
# MAIN
# ==============================================================================

def main():
    # Configura il logger
    logger = configura_logger()
    logger.info("=" * 60)
    logger.info("APPLICAZIONE AVVIATA")
    logger.info("=" * 60)

    # Setting environment
    gestore_ordini, magazzino, report, clienti = setting_environment(logger)

    while True:
        scelta = menu()

        # 1. INSERIMENTO ORDINI
        if scelta == '1':
          scelta_1 = menu_1()

          # 1.1 INSERIMENTO ORDINI MANUALI
          if scelta_1 == '1':
            cliente = input("Inserisci l'ID del Cliente:")
            logger.info(f"Registrazione ordine manuale per cliente: {cliente}")
            ordine = gestore_ordini.crea_e_registra_ordine_da_input(cliente)
            if ordine:
              logger.info(f"Ordine registrato: {ordine.id_ordine}")
              prodotti_critici = controlla_ordine_sotto_soglia(ordine, magazzino)
              if prodotti_critici:
                mostra_alert_sotto_soglia(prodotti_critici)
                logger.warning(f"Ordine {ordine.id_ordine} contiene {len(prodotti_critici)} prodotto/i sotto soglia")
            else:
              logger.warning(f"Registrazione ordine annullata per cliente: {cliente}")

          # 1.2 INSERIMENTO ORDINI DA CSV
          elif scelta_1 == '2':
            ordine_file = input('Inserire il path del file in formato .csv: ')
            logger.info(f"Importazione ordini da CSV: {ordine_file}")
            try:
              ordini_importati = gestore_ordini.import_ordini_csv(ordine_file)
              print(f"File importato correttamente. {len(ordini_importati)} ordini registrati.")
              logger.info(f"Importazione completata: {len(ordini_importati)} ordini importati")
              for ordine in ordini_importati:
                prodotti_critici = controlla_ordine_sotto_soglia(ordine, magazzino)
                if prodotti_critici:
                  logger.warning(f"Ordine {ordine.id_ordine} da CSV contiene {len(prodotti_critici)} prodotto/i sotto soglia")
              gestore_ordini.visualizza_ordini()
            except FileNotFoundError:
              print(f"File non trovato: {ordine_file}")
              logger.error(f"File CSV non trovato: {ordine_file}")
            except Exception as e:
              print(f"Errore durante importazione: {e}")
              logger.error(f"Errore durante importazione CSV: {e}")

          else:
              print("Scelta non valida, riprova.")

        # 2. VISUALIZZAZIONE O EVASIONE ORDINI
        elif scelta == '2':
          scelta_2 = menu_2()

          # 2.1 VISUALIZZAZIONE LISTA ORDINI
          if scelta_2 == '1':
            print("\n---- Visualizzazione ordini ----")
            ordini = gestore_ordini.visualizza_ordini()
            logger.info(f"Visualizzazione ordini richiesta: {len(ordini)} ordini totali")
            for ordine_str in ordini:
              print(ordine_str)

          # 2.2 EVASIONE ORDINI
          elif scelta_2 == '2':
            id_ordine = input("Inserisci l'ID dell'ordine da evadere: ")
            logger.info(f"Richiesta evasione ordine: {id_ordine}")
            try:
              messaggi = gestore_ordini.evadi_ordine(id_ordine, magazzino)
              for messaggio in messaggi:
                print(messaggio)
              logger.info(f"Ordine {id_ordine} evaso con successo")
            except Exception as e:
              print(f"Errore durante l'evasione dell'ordine {id_ordine}: {e}.")
              logger.error(f"Errore evasione ordine {id_ordine}: {e}")

          else:
            print("Scelta non valida, riprova.")

        # 3. STATO MAGAZZINO
        elif scelta == '3':
          scelta_3 = menu_3()

          # 3.1 STAMPA STATO MAGAZZINO
          if scelta_3 == '1':
            print('')
            print('---- Stampa stato magazzino ----')
            logger.info("Visualizzazione stato magazzino richiesta")
            magazzino.stampa_inventario()
            print('')

          # 3.2 MODIFICA GIACENZE MAGAZZINO
          elif scelta_3 == '2':
            # Caso in cui il magazzino è vuoto
            if magazzino.prodotti == {}:
              print("Il magazzino è vuoto.")
              logger.info("Tentativo modifica giacenze: magazzino vuoto")
              continue
            prodotto_codice = input("Inserisci il codice del prodotto da aggiornare: (es. PRO001) ")
            logger.info(f"Modifica giacenza richiesta per prodotto: {prodotto_codice}")
            try:
              try:
                prodotto = magazzino.cerca_prodotto_id(prodotto_codice)
              except ValueError as e:
                print(f"Errore: {e}")
                logger.warning(f"Prodotto non trovato: {prodotto_codice}")
                continue
              quantita = int(input(f"Inserisci la quantità da aggiungere (usa numero negativo per sottrarre): "))
              prodotto.aggiorna_giacenza(quantita)
              print(f"Giacenza aggiornata: {prodotto.giacenza} {prodotto.unita_misura}")
              logger.info(f"Giacenza {prodotto_codice} aggiornata di {quantita} unità. Nuova giacenza: {prodotto.giacenza}")
            except ValueError as e:
              print(f"Errore: {e}")
              logger.error(f"Errore modifica giacenza {prodotto_codice}: {e}")

          # 3.3 RICERCA PRODOTTO
          elif scelta_3 == '3':
            print('---- Ricerca prodotto ----')
            chiave_ricerca = menu_3_3()

            # 3.3.1 RICERCA PRODOTTO PER CODICE
            if chiave_ricerca == "1":
              codice_prodotto = input('Inserisci il codice del prodotto: ')
              logger.info(f"Ricerca codice '{codice_prodotto}'")
              try:
                prodotto = magazzino.cerca_prodotto_id(codice_prodotto)
                print(prodotto)
                logger.info(f"Ricerca codice '{codice_prodotto}': prodotto trovato")
              except ValueError as e:
                print(f"Errore: {e}")
                logger.info(f"Ricerca codice '{codice_prodotto}': prodotto non trovato")

            # 3.3.2 RICERCA PRODOTTO PER CATEGORIA
            elif chiave_ricerca == "2":
              categoria_prodotto = input("Inserisci la categoria dell'oggetto: ")
              logger.info(f"Ricerca prodotti per categoria: {categoria_prodotto}")
              try:
                prodotto = magazzino.cerca_prodotto_categoria(categoria_prodotto)
                print("\n".join(prodotto))
                logger.info(f"Ricerca categoria '{categoria_prodotto}': {len(prodotto)} prodotto/i trovato/i")
              except ValueError as e:
                print(f"Errore: {e}")
                logger.info(f"Ricerca categoria '{categoria_prodotto}': nessun risultato")

            # 3.3.3 RICERCA PRODOTTO PER SOGLIA
            elif chiave_ricerca == "3":
              soglia_riordino = int(input("Inserisci la soglia di riordino: "))
              logger.info(f"Ricerca prodotti con giacenza <= {soglia_riordino}")
              prodotto = magazzino.cerca_prodotto_giacenza(soglia_riordino)
              if prodotto:
                print("\n".join(prodotto))
                logger.info(f"Ricerca giacenza: {len(prodotto)} prodotto/i sotto soglia {soglia_riordino}")
              else:
                print(f"Nessun prodotto trovato con giacenza inferiore a {soglia_riordino}")
                logger.info(f"Ricerca giacenza {soglia_riordino}: nessun risultato")
            else:
              print("Scelta non valida, riprova.")

        # 4. CREAZIONE O STAMPA REPORT
        elif scelta == '4':
          logger.info("Generazione report richiesta")
          nome_file = report.genera_report(gestore_ordini, magazzino)
          print("\n"+nome_file)

          # 4.1 ESPORTAZIONE REPORT
          input_scelta_5 = input("Vuoi esportare il report? [s/n]: ")
          if input_scelta_5.lower() == 's':
            nome_file = report.esporta_report_txt(gestore_ordini, magazzino, nome_file=f"report_{datetime.now().date()}.txt")
            print(f"Report salvato in 'report_{datetime.now().date()}.txt'.")
            logger.info(f"Report esportato in file: {nome_file}")
          else:
            logger.info("Esportazione report annullata")
            continue

        # 5. EXPORT / IMPORT DB IN FORMATO JSON
        elif scelta == '5':
          scelta_5 = menu_5()

          # 5.1 ESPORTAZIONE MAGAZZINO IN FORMATO JSON
          if scelta_5 == '1':
            print('Creazione magazzino in formato json...')
            nome_file_json = f'inventario_{datetime.now().date()}.json'
            magazzino.esporta_inventario_json(nome_file=nome_file_json)
            print('Report salvato correttamente.')
            logger.info(f"Inventario esportato in JSON: {nome_file_json}")

          # 5.2 IMPORTAZIONE INVENTARIO DA JSON
          elif scelta_5 == '2':
            print('Importazione magazzino da json...')
            nome_file_json = input('Inserire il path del file in formato .json: ')
            try:
              magazzino.importa_inventario_json(nome_file=nome_file_json)
              print('Report importato correttamente.')
              logger.info(f"Inventario importato da JSON: {nome_file_json}")
            except FileNotFoundError:
              print(f"File non trovato: {nome_file_json}")
              logger.error(f"File JSON non trovato per import: {nome_file_json}")
            except Exception as e:
              print(f"Errore durante importazione: {e}")
              logger.error(f"Errore importazione JSON: {e}")

          # 5.3 ESPORTAZIONE LISTA ORDINI IN FORMATO JSON
          elif scelta_5 == '3':
            print('Esportazione lista ordini in formato json...')
            nome_file_json = gestore_ordini.esporta_ordini_json()
            print(f'Report {nome_file_json} salvato correttamente.')
            logger.info(f"Ordini esportati in JSON {nome_file_json}")

          # 5.4 IMPORTAZIONE LISTA ORDINI DA JSON
          elif scelta_5 == '4':
            print('Importazione lista ordini da json...')
            nome_file_json = input('Inserire il path del file in formato .json: ')
            try:
              gestore_ordini.import_ordini_json(nome_file=nome_file_json)
              print("Import avvenuto con successo.")
              logger.info(f"Ordini importati con successo.")
            except FileNotFoundError:
              print(f"File non trovato: {nome_file_json}")
              logger.error(f'File JSON non trovato per import: {nome_file_json}')
            else:
              print(f"Errore durante l'importazione: {e}")
              logger.error(f"Errore durante l'importazione: {e}")

          else:
            print("Scelta non valida, riprova.")

        # 0. USCITA
        elif scelta == '0':
            print("Uscita.")
            logger.info("Applicazione chiusa")
            logger.info("=" * 60)
            break
        
        else:
            print("Scelta non valida, riprova.")
            logger.warning(f"Scelta menu principale non valida: {scelta}")

main()

"""
================================================================================
ISTRUZIONI D'USO
================================================================================

AVVIO DEL PROGRAMMA:
-------------------
1. Eseguire il comando: python esame.py
2. Il sistema inizializza automaticamente:
   - 4 clienti di esempio (ROSSI, VERDI, GIALLI, VIOLA)
   -  prodotti di esempio (P001-P007)
   - Sistema di logging (app.log)

MENU PRINCIPALE:
---------------
1. Registrazione nuovi ordini
   1.1 Manuale: inserimento interattivo con verifica disponibilità
   1.2 Da CSV: import massivo da file (vedi formato sotto)

2. Visualizza o evadi ordini
   2.1 Visualizza: lista completa ordini con stato
   2.2 Evadi: processa ordine e aggiorna giacenze

3. Consultazione magazzino
   3.1 Visualizza inventario completo
   3.2 Modifica giacenze manualmente
   3.3 Ricerca prodotti (per codice/categoria/giacenza)

4. Creazione report
   Genera report giornaliero
   - Opzione esportazione in TXT

5. Salvataggio DB in JSON
   5.1 Esporta stato magazzino in JSON
   5.2 Importa stato magazzino da JSON
   5.3 Esporta lista ordini in JSON
   5.4 Importa lista ordini da JSON

0. Esci

FORMATO ORDINE DI ESEMPIO:
ORD001,ROSSI,2024-06-01,"{'P001': 10, 'P002': 5}"

Note:
- id_cliente deve esistere nel sistema, altrimenti viene richiesta la creazione di una nuova anagrafica cliente
- Formato data: YYYY-MM-DD

ESEMPI D'USO:
-------------
1. Registrare un ordine manualmente:
   Menu 1 -> 1 -> inserire dati richiesti

2. Registrare un ordine da CSV:
   Menu 1 -> 2 -> inserire path file (es: ordini_esempio.csv)

3. Visualizzare gli ordini:
   Menu 2 -> 1 (lista completa ordini)

4. Evadere un ordine:
   Menu 2 -> 2 -> inserire ID ordine

5. Verificare prodotti magazzino:
   Menu 3 -< 1 (prodotti con * necessitano riordino)

6. Generare report:
   Menu 4 -> s (per salvare)

7. Esportare magazzino in JSON:
   Menu 5 -> 1 (crea file json)

================================================================================"""